[package]
name = "hardware-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bool-algebra = { git = "https://github.com/eelias13/bool-algebra", version = "0.1.0" }
graph = { git = "https://github.com/eelias13/graph", version = "0.1.0" }
